//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFIRKK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int uId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LogText { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
