//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFIRKK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public int uId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public Nullable<int> TattooCount { get; set; }
        public Nullable<decimal> TattooPrice { get; set; }
        public Nullable<decimal> TattooPricePoints { get; set; }
        public Nullable<bool> TattooPriceType { get; set; }
        public Nullable<int> PiercingCount { get; set; }
        public Nullable<decimal> PiercingPrice { get; set; }
        public Nullable<decimal> PiercingPricePoints { get; set; }
        public Nullable<bool> PiercingPriceType { get; set; }
        public Nullable<int> MishaCount { get; set; }
        public Nullable<decimal> MishaPrice { get; set; }
        public Nullable<decimal> MishaPricePoints { get; set; }
        public Nullable<bool> MishaPriceType { get; set; }
        public Nullable<int> NeckleCount { get; set; }
        public Nullable<decimal> NecklePrice { get; set; }
        public Nullable<decimal> NecklePricePoints { get; set; }
        public Nullable<bool> NecklePriceType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<double> PointsSum { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
